services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile.prd
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prd
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend:${SERVICE_PORT}'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_TTL: ${COOKIE_TTL}

  database:
    container_name: database
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    volumes:
      - ./persist/db-prd:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
