FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM nginx:stable-alpine
COPY gateway/nginx.prd.conf /etc/nginx/templates/default.conf.template
COPY --from=frontend-builder /app/dist /usr/share/nginx/html
CMD ["nginx","-g","daemon off;"]
