FROM node:20-alpine AS backend-builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src/ ./
RUN npm run build

FROM node:20-alpine
# RUN apk --no-cache add curl
WORKDIR /app
COPY --from=backend-builder /app/package*.json ./
RUN npm ci --only=production
COPY --from=backend-builder /app/dist ./dist
CMD ["npm","run","start"]