FROM node:20-alpine AS backend-builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src/ ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=backend-builder /package*.json ./
RUN npm ci --only=production
COPY --from=backend-builder /app/dist ./dist
CMD ["node","dist/index.js"]